### ISSUE TITLE
Problem with XLPMacroOptions2010

### ISSUE THREAD

**Issue by EricE** [ericremoreynolds/excelpython#14]
Hi Eric,
I was getting an error in this sub when importing UDFS (in Excel 2010), "Method 'MacroOptions' of object '_Application' failed".  I tracked it down to a verbose doc string; it looks like desc can only be 255 characters long.  I've made the below fix and life is good:

```
Sub XLPMacroOptions2010(macroName As String, desc, argdescs() As String)
If Len(desc) > 255 Then
    desc = Left$(desc, 255)
End If
    Application.MacroOptions macroName, Description:=desc, ArgumentDescriptions:=argdescs
End Sub
```

Thanks for the good work,
Eric

**Comment by ozonosphere** [comment]
Hey Eric, when is the next release which will solve this problem? 

I am having this issue and cannot solve it even after modifying the code in the xlam file

i appreciate it if you could get back to me

**Comment by ericremoreynolds** [comment]
Hi ozonosphere,

Actually this fix has been included in previous releases quite a long time ago: the 255 character truncation code is present in the latest release as you can see [here](https://github.com/ericremoreynolds/excelpython/blob/master/addin/xlpython_xlam_vba_code.bas#L282-L287).

Please let me know what issues you're encountering.

Regards,

Eric

**Comment by ozonosphere** [comment]
Hey Eric
Thanks for replying

I have reinstall the latest version, however, the problem still exists when I try to import the following add-in function:

```
from xlpython import *
import numpy as np

@xlfunc
@xlarg("array","nparray")

def GetBoostrapedNull(array,no_of_events):
    size_1d = array.size
    data_reshape_1d = np.reshape(array, size_1d)
    random_N_events = np.random.choice(data_reshape_1d,no_of_events)
    average = np.average(random_N_events)
    return average
```

if you could help me, that would be great.
I am using Canopy btw.
Charles
