### ISSUE TITLE
Setup error

### ISSUE THREAD

**Issue by adolfo158** [ericremoreynolds/excelpython#22]
When I click on the Setup Excel Python Smily I get a window saying "error 1004" in execution time  (translation from Spanish). I get two buttons: One to end, and the other to "depurar" which I think it means clean the code and a  Visual Basic GUI opens highlighting the following code:

On Error GoTo 0
        wb.VBProject.VBComponents.Import wb.Path + Application.PathSeparator + "xlpython" + Application.PathSeparator + "xlpython.bas"

***\* which is part of the following code module:

 End If
            Next f
            If Not isVersionOK Then
                MsgBox "The installation folder already exists, but it does not contain ExcelPython version " + ver + "." _
                    + vbCrLf + vbCrLf + "Installation folder: " + wb.Path + Application.PathSeparator + "xlpython" _
                    + vbCrLf + vbCrLf + "To set up a fresh install please delete it and try again. Note that you may need to close Excel to delete it." _
                    , vbCritical, "Error installing ExcelPython runtime"
                Exit Sub
            End If
        Else
            fso.CopyFolder ThisWorkbook.Path + Application.PathSeparator + "xlpython", wb.Path + Application.PathSeparator + "xlpython"
        End If

```
    On Error GoTo not_present
    wb.VBProject.VBComponents.Remove wb.VBProject.VBComponents("xlpython")
```

not_present:
        On Error GoTo 0
        wb.VBProject.VBComponents.Import wb.Path + Application.PathSeparator + "xlpython" + Application.PathSeparator + "xlpython.bas"

```
    ' create skeleton py file
    Set fso = CreateObject("Scripting.FileSystemObject")
    If Not fso.FileExists(wb.Path + Application.PathSeparator + fso.GetBaseName(wb.name) + ".py") Then
        Set f = fso.CreateTextFile(wb.Path + Application.PathSeparator + fso.GetBaseName(wb.name) + ".py", True)
        f.WriteLine "from xlpython import *"
        f.Close
    End If
    'MsgBox "You can now write user-defined functions for this workbook in Python in the file '" + wb.Path + Application.PathSeparator + fso.GetBaseName(wb.Name) + ".py'." + vbCrLf + "Please consult the online docs for more information on how it works.", Title:="ExcelPython setup successful!"
End If
```

End Sub

Sub XLPMacroOptions2010(macroName As String, desc, argdescs() As String)
    Application.MacroOptions macroName, Description:=desc, ArgumentDescriptions:=argdescs
End Sub

**Comment by kalbhairab** [comment]
![error](https://cloud.githubusercontent.com/assets/12480299/11013477/431164bc-8537-11e5-82f2-35cf087f0ccb.JPG)

I got this error when trying to <b>import python udfs</b>

**Comment by ericremoreynolds** [comment]
Hello @kalbhairab, have you tried consulting the log as suggested by the error message?
KR
Eric
