### ISSUE TITLE
xlpython.log file is locked

### ISSUE THREAD

**Issue by charliegenge** [ericremoreynolds/excelpython#33]
Hi Eric,

I'm running two separate excel sessions in the same folder, which both use the excelpython functionality. I'm finding that when I try to run some of the python functionality from either session, I have to end the pythonw.exe process or I get a "could not open .....xlpython.log for redirection" error.
Is there a way to avoid this?

Thanks,

Charlie

**Comment by ericremoreynolds** [comment]
Please check out xlwings, this shouldn't be an issue any more.
