### ISSUE TITLE
Run-time error '-2147467259 (80004005)':

### ISSUE THREAD

**Issue by atrulz2** [ericremoreynolds/excelpython#46]
Hi Eric,

I upgraded my pythonexcel from version 1 to version 2 and likewise updated the code. However, now my program returns the error.

Run-time error '-2147467259 (80004005)':

Automation Error
Unspecified Error

![error](https://cloud.githubusercontent.com/assets/5519462/6321996/ccb61294-bb02-11e4-9b98-a9d567e3c34c.png)

code is simple:

Set res = Py.Call(Py.Module("order_dups"), "duplicate_order", _
                Args:=Py.Tuple(ActiveSheet.Cells(row, 1).Value))

Any ideas?

**Comment by ericremoreynolds** [comment]
Hello,

I believe the problem is the `Args:=` keyword argument - in ExcelPython v2 you do not need to specify it, in fact the following should work:
```vb.net
Set res = Py.Call(Py.Module("order_dups", "duplicate_order", _
Py.Tuple(ActiveSheet.Cells(row, 1).Value))
```
Please let me know if this fixes the problem!

Regards,

Eric.

**Comment by atrulz2** [comment]
that worked flawlessly Eric. Thanks.

Also could you tell me whats wrong with this code.

I am now trying to specify the path of the module like your old < v2 code. where the module is a different folder as the workbook. The path of the python module is in the PyPath variable.

Set res = Py.Call(Py.Module("order_dups", PyPath), "duplicate_order", _
                Py.Tuple(ActiveSheet.Cells(row, 1).Value))

Returns:

![error](https://cloud.githubusercontent.com/assets/5519462/6326301/17e9e3b8-bb48-11e4-84a3-1bb47dd96136.png)

Thanks so much.

**Comment by ericremoreynolds** [comment]
Hi,

So in V2 the environment setup works a bit differently - the best place to specify additional Python search paths is in the `xlpython.cfg` file, if you open it up it should all be pretty self-explanatory, also if you look at [this doc](https://github.com/ericremoreynolds/excelpython/blob/master/docs/tutorials/Configuration01.md) it should give u some hints.

If you need any more pointers let me know!

Regards,

Eric.

**Comment by atrulz2** [comment]
It works Eric.

Thanks.
