### ISSUE TITLE
replace c/c++ code with cython

### ISSUE THREAD

**Issue by denfromufa** [ericremoreynolds/excelpython#49]
Eric, have you considered replacing c code part of this project with cython?

**Comment by denfromufa** [comment]
The main reason is because this is quite pythonic, hydrid mode, and automatic wrappers exist

**Comment by ericremoreynolds** [comment]
Hi Denis,

I took a quick look at Cython not long ago, not for ExcelPython but for other purposes. Do you think it would make sense for ExcelPython? The C++ part of the EP code doesn't actually depend on Python right now... my thinking is that Cython makes more sense for writing `.pyd` modules, not so much for DLLs which are independent of Python.

Let me know what you think.

Regards,

Eric.

**Comment by denfromufa** [comment]
this issue applies to expy more than excelpython i guess.
