### ISSUE TITLE
Error running macro in ImportPythonUDFs

### ISSUE THREAD

**Issue by mathiasime** [ericremoreynolds/excelpython#56]
Hello Eric,

I have downloaded and installed ExcelPython and Anaconda, setted-up ExcelPython and permanently installed xlam inside Office.

When I run "Import Python UDFs" I get:
"Run-time error '1004'
Cannot run the macro "cod.xslm'!Py'. The macro may not be available in this workbook or all macros may be disabled."

When I debug, find the error inside Sub ImportPythonUDFs (control as IRibbonControl) on the line that "Set Py = Application.Run(" ' " + wb.name + " ' ! Py")" (**without the spaces) because that adresses nowhere.

Can you help me?

**Comment by ericremoreynolds** [comment]
Is your workbook file really called cod.xslm instead of .xlsm? If so that
could be the problem, perhaps Excel doesn't allow macros to be run unless
the workbook's file extension is one of the macro-enabled ones.

**Comment by mathiasime** [comment]
Tks for the fast answer, Eric

My mistake, tipped it wrong: that's "...cod.xlsm...".

All my macros are enabled and the names of the files are "cod.xlsm" and "cod.py", both in the same folder.

**Comment by ericremoreynolds** [comment]
Hi Mathias,

Sorry for this slow reply after my quick reply :frowning:

So I'm not really sure why you are having that problem, I have never encountered it nor have I heard of anyone else experiencing this problem. As you can probably guess, `Application.Run("'" + wb.name + "'!Py")` calls the `cod.xlsm!Py` VBA macro, and indeed this function should be defined in your `cod.xlsm` workbook. If it isn't, I suspect what might have happened is that you ran 'Setup Workbook' then didn't save it. To fix the problem it should be sufficient to just re-run it.

Let me know if that helps.

Regards,

Eric.

**Comment by mathiasime** [comment]
Hello Eric,

It worked! My mistake was that I always clicked setup and then import without saving.

I wrote a code with around 10 different functions but I can only call the first function, ExcelPython don't allow me to call the others. Tried to put "@xlfunc" before each function but I returns me:

"Run-time error '1004':
Method 'MacroOptions' of object '_Application' failed" 

and when I debug, it drives me to Sub XLPMacroOptions2010

How can I call more than one function from my py code?

Tks a lot!

**Comment by ericremoreynolds** [comment]
Hi Mathias,

Can you try attaching your code or a part of it? It's a bit difficult to analyse without seeing exactly what you're doing. Usually ExcelPython should have no problem exposing multiple functions defined in the same Python script.

Regards,

Eric

**Comment by mathiasime** [comment]
Hello Eric

Above is an extract of my code, actually I have a py code that contains just functions, 9 of them, and I would like to make all of them useful in excel.

What would you say about that?

Tks!




    def mnorm(x):
    y = abs(x)
    if y > 37:
        mnorm1 = 0
    else:
        expo =exp(-pow(y,2) / 2)

        if y < 7.07106781186547:
            SumA = 0.0352624965998911 * y + 0.700383064443688
            SumA = SumA * y + 6.37396220353165
            SumA = SumA * y + 33.912866078383
            SumA = SumA * y + 112.079291497871
            SumA = SumA * y + 221.213596169931
            SumA = SumA * y + 220.206867912376
            SumB = 0.883883476648318 * y + 1.75566716318264
            SumB = SumB * y + 16.064177579207
            SumB = SumB * y + 86.7807322029461
            SumB = SumB * y + 296.564248779674
            SumB = SumB * y + 637.333633378831
            SumB = SumB * y + 793.826512519948
            SumB = SumB * y + 440.413735824752
            mnorm1 = expo * SumA / SumB
        else:
            SumA = y + 0.65
            SumA = y + 4 / SumA
            SumA = y + 3 / SumA
            SumA = y + 2 / SumA
            SumA = y + 1 / SumA
            mnorm1 = expo/ (SumA * 2.506628274631)

        if x > 0: 
            mnorm1 = 1 - mnorm1 

    return mnorm1

    def x1(futuro, strike, vol50, DU):
    futuro=float(futuro)
    strike=float(strike)
    x=log10((futuro/strike)+0.5*pow(vol50,2)*DU/252.)/(vol50*sqrt(DU/252.))
    return x

    def x2(futuro, strike, vol50,DU):
    futuro=float(futuro)
    strike=float(strike)
    x=x1(futuro, strike, vol50, DU)-vol50*sqrt(DU/252.)
    return x

**Comment by ericremoreynolds** [comment]
1) the code as you've written it has an indentation problem which makes it non-valid Python, but I am assuming that is just an indentation problem

2) I can confirm that you need to decorate every function you wish to use from Excel with `@xlfunc` like so:
```
from xlpython import xlfunc

@xlfunc
def mnorm(x):
    y = abs(x)
    # ... more code here ...
    return mnorm1

@xlfunc
def x1(futuro, strike, vol50, DU):
    futuro=float(futuro)
    strike=float(strike)
    x=log10((futuro/strike)+0.5*pow(vol50,2)*DU/252.)/(vol50*sqrt(DU/252.))
    return x

@xlfunc
def x2(futuro, strike, vol50,DU):
    futuro=float(futuro)
    strike=float(strike)
    x=x1(futuro, strike, vol50, DU)-vol50*sqrt(DU/252.)
    return x
```
Once you have done this, you should click the `Import Python UDFs` button in the toolbar and then you should have the functions available for use in your workbook.

Let me know how you get on.

Rgds

**Comment by mathiasime** [comment]
Hello Eric

If I put "@xlfunc" before each function it returns me:

"Run-time error '1004':
Method 'MacroOptions' of object '_Application' failed"

and when I debug, it drives me to Sub XLPMacroOptions2010

Not worked =/

**Comment by ericremoreynolds** [comment]
Hi Mathias,

I have identified the problem - it is the functions `x1` and `x2`. These look like Excel cell addresses so Excel does not allow them. Rename them to something else (for example `x_1`) and they should work.

Hope this fixes your problems, kind regards,

Eric
