### ISSUE TITLE
Anyway to avoid needing the xlpython folder?

### ISSUE THREAD

**Issue by rbn920** [ericremoreynolds/excelpython#62]
I use a lot of spreadsheets and I am finding I can develop them much faster with excelpython but I am getting tired of all the extra files needed. Is it possible to put all my .py files as well as the xlpython folder in one place and have my spreadsheets call them from there? It seemed obvious enough looking at the xlpython module but it didnt seem to work.

**Comment by rbn920** [comment]
So I did get it to work. I just had to re-import the UDF's.

**Comment by bscalzo** [comment]
Can you share the changes to the VBA code? I'm currently trying to achieve this too..

**Comment by fzumstein** [comment]
Note that ExcelPython is now part of https://github.com/ZoomerAnalytics/xlwings and this feature has been implemented there.
