### ISSUE TITLE
ExcelPython add-in

### ISSUE THREAD

**Issue by AdolfoMenaVillar** [ericremoreynolds/excelpython#63]
Hi Eric!,

My name is Adolfo and I'm writting this from Chile, SouthAmerica.

I have just one question about the ExcelPython, ¿It is possible to use the VBA code generated from Python as an Excel add-in in a computer without Python (and of course without ExcelPython) ?

My idea is to create the VBA code with ExcelPython and save it as an Excel add-in and send it to several people who have not installed (and doesn't know) neither Python or VBA, so they can use simple modules in their's spreedsheets

Thank you!

**Comment by ericremoreynolds** [comment]
Hello Adolfo,

This is indeed possible, however it's not very easy currently. Please checkout xlwings (ExcelPython has now been deprecated) for this functionality in future.

Regards,

Eric
