### ISSUE TITLE
description of the arguments of an UDF

### ISSUE THREAD

**Issue by Fabien33000** [ericremoreynolds/excelpython#64]
Is there a way, with ExceLPython, to provide a short description of the arguments of an UDF function that can appear in excel when we use this UDF function ?

**Comment by ericremoreynolds** [comment]
Hi Fabien,

Yes this is indeed possible, the syntax is as follows:
```python
from xlpython import *

@xlfunc
@xlarg("x", doc="This argument is pronounced 'ex'")
@xlarg("y", doc="This argument is pronounced 'why'")
def double_sum(x, y):
    """Returns twice the sum of the arguments"""
    return 2.0 * (x + y)
```

Let me know if you have any further question.

Kind regards,

Eric.
