### ISSUE TITLE
Memory error

### ISSUE THREAD

**Issue by rbn920** [ericremoreynolds/excelpython#65]
I have a function that returns a list of 99 values consisting of floats and strings. when the list is sent back to excel excel complains with "MemoryError: CreatingSafeArray". The function works fine in python alone. I also had this problem with other functions in the past and was able to work around it by using some of the numpy dtypes such as float16. The problem here is that the list contains strings as well so it cannot easily be converted.

**Comment by fzumstein** [comment]
Can you post a minimal code sample to reproduce this?

**Comment by rbn920** [comment]
```python
from xlpython import xlfunc
import numpy as np

@xlfunc
def mMoment(dist_load, point_load, point_location, length, reaction_a):
    '''Returns max moment from simple span beam with uniform distributed
    load and point load. Uses the Macaulay Method'''

    numsteps = 1000
    xvalues = np.linspace(0, length, num=numsteps)
    moment = [(reaction_a * x - dist_load * x ** 2 / 2 - point_load *
               max([0.0, x - point_location])) for x in xvalues]
    return max(moment)

@xlfunc
def multi_mMoment(dist_loads, point_loads, point_location, length,
                  reactions_a):
    ''' Calls mMoment for size of selection'''

    moment = [mMoment(w, P, point_location, length, r) for w, P, r in
              zip(dist_loads, point_loads, reactions_a)]
    return moment
```
If multi_mMoment is used it will return the memory error unless the list "moment" is converted to ints or float16 etc. dist_loads, point_loads, and reactions_a are equal length ranges. point_location and length are single values.

**Comment by rbn920** [comment]
I did  a bit more experimenting. I converted my function over to a macro and used xlwings and received the same error
```
---------------------------
Error
---------------------------
Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "Y:\dev\de_wood_headers\beams_xlw.py", line 452, in main

    Range('Design', 'CG19').value = test_out

  File "C:\Users\Robby\Anaconda3\lib\site-packages\xlwings\main.py", line 866, in value

    self.row1, self.col1, row2, col2), data)

  File "C:\Users\Robby\Anaconda3\lib\site-packages\xlwings\_xlwindows.py", line 269, in set_value

    xl_range.Value = data

  File "C:\Users\Robby\Anaconda3\lib\site-packages\win32com\client\dynamic.py", line 560, in __setattr__

    self._oleobj_.Invoke(entry.dispid, 0, invoke_type, 0, value)

MemoryError: CreatingSafeArray
```
Also, if I convert the entire list to strings prior to sending it back to excel it works with no issues. This seems to be of little consequence once the values are in excel as it treats them as numbers but it does mean that I need to have separate code to run in (pure)python vs excel.

**Comment by fzumstein** [comment]
ExcelPyhton and xlwings both use pywin32 underneath, so that makes sense as it's actually an issue in that library. Numpy scalars seem to be the issue: http://stackoverflow.com/questions/18136870/win32com-memoryerror-attempting-to-insert-data-into-excel

see also: https://github.com/ZoomerAnalytics/xlwings/issues/19
