### ISSUE TITLE
Run-time error '1000'

### ISSUE THREAD

**Issue by TheBestRevengeIsMassiveSuccess** [ericremoreynolds/excelpython#68]
I have tried to follow the quick start tutorial at 

http://ericremoreynolds.github.io/excelpython/quickstart/

But when I get to the point of importing Python UDFs, I get the following error:

![image](https://cloud.githubusercontent.com/assets/25950129/23203934/b9baea54-f938-11e6-80a5-e2d0e09e2adc.png)

I have studied the fixes in 
 
https://github.com/ericremoreynolds/excelpython/blob/master/docs/tutorials/AddinTrouble.md
https://github.com/ericremoreynolds/excelpython/issues/57

I have tried to add the full file path to pythonw.exe (note the path in the error message above). I have also updated my user PythonPath to include file for my project.

So I think I may have excluded the inability to find pythonw.exe, so hopefully there are other ideas. Thanks very much, great concept for embedding Python in Excel and I'm keen to get into it.

**Comment by fzumstein** [comment]
We have integrated ExcelPython in xlwings, please see https://www.xlwings.org/ and https://github.com/ZoomerAnalytics/xlwings
