### ISSUE TITLE
ExcelPython installation issue

### ISSUE THREAD

**Issue by emughini** [ericremoreynolds/excelpython#70]
Hello,
I had an issue while installing ExcelPython:
1) I run the "Setup Excel Python" procedure - All Good
2) I run then the "Import Python UDFs" procedure - Error message

However, I received an error message (reported below) 
![image](https://user-images.githubusercontent.com/47175505/51973510-19de7780-247e-11e9-82d5-c8d4804710ce.png)

I've checked and confirm the presence of the file:
C:\Users\J0538992\AppData\Roaming\Microsoft\Windows\Network Shortcuts\xlpython\xlpyserver.py

I tried to repeat the installation from another drive (H:\ExcelPython) but I received the same error:
![image](https://user-images.githubusercontent.com/47175505/51975016-8a3ac800-2481-11e9-901c-4c88d5560ae1.png)

I am not sure how to complete the installation. Could anybody help? 
Thanks,
Manuel

**Comment by fzumstein** [comment]
Hi Manuel, ExcelPython is now part of https://github.com/ZoomerAnalytics/xlwings and we are not supporting ExcelPython anymore.
