### ISSUE TITLE
ExcelPython for Excel 2011 on Mac?

### ISSUE THREAD

**Issue by ifuchs** [ericremoreynolds/excelpython#72]
Any chance we will see a version of ExcelPython for the Mac? If not, is there another solution that works on Excel 2011?

**Comment by fzumstein** [comment]
As per readme, ExcelPython has been integrated in xlwings (which works also with Mac except for UDFs): https://github.com/xlwings/xlwings

**Comment by ifuchs** [comment]
Thanks. Can I (effectively) do a UDF on the Mac by creating a VBA function that calls Python and then using that in a cell?

**Comment by fzumstein** [comment]
no, this will be too slow. currently there's no way to make udfs work on
mac.
