### ISSUE TITLE
ExcelPython Installation

### ISSUE THREAD

**Issue by PetrusvMintek** [ericremoreynolds/excelpython#73]
Hi,

I installed ExcelPython. Now I have the ExcelPython tab on my toolbar (in a macro-enables workbook).
Running the "SetupExcelPython" button does not seem to create any problem, an ExcelPython module appears in the VBA Window.
There also appears an ExcelPython directory in the same directory as the Excel workbook.

My first concern is that when I look in VBA-Tools-References, I see no ExcelPython reference listed there. But pushing on:

As per the example, I create a Python script using Spyder(anaconda3) bearing the code for an "@xl func" called doubleSum.
Back in Excel, I now press the "Import Python UDFs" button, and get a "Runtime-1000" error message. The log file states 

Traceback (most recent call last):
  File "C:\Users\PetrusV\Documents\Anaconda & Python\xlpython\xlpyserver.py", line 3, in <module>
    import _win32sysloader
ImportError: No module named '_win32sysloader'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\PetrusV\Documents\Anaconda & Python\xlpython\xlpyserver.py", line 5, in <module>
    raise Exception("Cannot import PyWin32. Are you sure it's installed?")
Exception: Cannot import PyWin32. Are you sure it's installed?

So there seem to be some files missing. Yet my Spyder on its own works fine. Have been searching the web but nobody seems to be experiencing this particular problem.

**Comment by fzumstein** [comment]
ExcelPython is now part of xlwings, see your issue there: https://github.com/xlwings/xlwings/issues/1441
