### ISSUE TITLE
pywin32 error

### ISSUE THREAD

**Issue by leyojoseph** [ericremoreynolds/excelpython#74]
Hello,
Getting below error ==>
![image](https://user-images.githubusercontent.com/67446653/135666849-a0518a9a-d074-488b-a32d-edee9025f6ac.png)

Traceback (most recent call last):
  File "C:\Tools\Excel_PA\Zodiac\xlpython\xlpyserver.py", line 5, in <module>
    raise Exception("Cannot import PyWin32. Are you sure it's installed?")
Exception: Cannot import PyWin32. Are you sure it's installed?

**Comment by leyojoseph** [comment]
![image](https://user-images.githubusercontent.com/67446653/135667081-e95bf5e1-ecae-4899-abd6-7c99280b4c65.png)

**Comment by fzumstein** [comment]
ExcelPython is now part of https://github.com/xlwings/xlwings
